name: handson-ml2
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip==19.1.1
    - nb_conda_kernels==2.2.2

    ##### Core scientific packages
    - matplotlib==3.0.3
    - numpy==1.16.2
    - pandas==0.24.1
    - scipy==1.1.0

    ##### Machine Learning packages
    - scikit-learn==0.20.3

    # Optional: the XGBoost library is only used in the ensemble learning chapter.
    - py-xgboost==0.82

    ##### Deep Learning packages

    ##### Image manipulation
    - imageio==2.5.0
    - Pillow==5.4.1
    - scikit-image==0.14.2

    ##### Extra packages (optional)

    # Joblib is a set of tools to provide lightweight pipelining
    - joblib==0.13.2

    # May be useful with Pandas for complex "where" clauses (e.g., Pandas
    # tutorial).
    - numexpr==2.6.9

    # Optional: this library can be useful in the classification chapter, exercise 4.
    - nltk==3.4.5

    # Needed in chapter 19.
    - requests==2.22.0

    # Optional: nice utility to diff Jupyter Notebooks.
    - nbdime==1.0.5

    # Optional: tqdm displays nice progress bars, ipywidgets for tqdm's notebook support
    - tqdm==4.31.1
    - ipywidgets==7.4.2

    - pip:
      ##### Machine Learning packages

      ##### TensorFlow-related packages

      # Replace tensorflow with tensorflow-gpu if you want GPU support. If so,
      # you need a GPU card with CUDA Compute Capability 3.5 or higher support, and
      # you must install CUDA, cuDNN and more: see tensorflow.org for the detailed
      # installation instructions.

      # - tf-nightly-2.0-preview
      - tf-nightly-gpu-2.0-preview

      #tensorboard
      - tb-nightly

      #tensorflow-datasets
      - tfds-nightly

      - tensorflow-hub

      # Optional: only used in chapter 13.
      - tensorflow-transform==0.13.0

      # # Optional: only used in chapter 16.
      # # At the present (April 2019) the TF Addons library is only available on Linux
      # # So uncomment this line if you are using Linux.
      # - tensorflow-addons

      # Optional: the TF Agents library is only needed in chapter 18
      - tf-agents-nightly

      # # Optional: the TF Serving API library is just needed for chapter 19.
      # - tensorflow-serving-api

      ##### Deep Learning packages

      # Optional: OpenAI gym is only needed for the Reinforcement Learning chapter.
      # There are a few dependencies you need to install first, check out:
      # https://github.com/openai/gym#installing-everything
      # - gym[all]==0.10.9
      # If you only want to install the Atari dependency, uncomment this line instead:
      - gym[atari]==0.10.9

      ##### Extra packages (optional)

      # Optional: this library can be useful in the classification chapter, exercise 4.
      - urlextract==0.8.3

      # Optional: this extension is handy to easily start/stop tensorboard
      # server(s) directly from Jupyter.
      - jupyter-tensorboard==0.1.8

      # Optional: these are useful Jupyter extensions, in particular to display the
      # table of contents
      - jupyter-contrib-nbextensions==0.5.0
